{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "kubemq.fullname" . }}
  labels:
    app: {{ include "kubemq.fullname" .  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  KUBEMQ_TOKEN: {{ .Values.token | quote }}
  {{- if .Values.licenseData }}
  KUBEMQ_LICENSE_DATA: {{ .Values.licenseData | quote }}
  {{ end }}
{{ end }}
