# https://taskfile.dev

version: '2'

tasks:
  release:
    cmds:
      - helm package kubemq -d ./docs
      - helm package dashboard -d ./docs
      - helm package connector -d ./docs
      - helm repo index ./docs
