NAME: kubemq
LAST DEPLOYED: Mon Jan 13 16:25:49 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: kubemq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubemq
  labels:
    app: kubemq
    chart: "kubemq-0.3.0"
    release: "kubemq"
    heritage: "Helm"
type: Opaque
stringData:
  LICENSE_KEY_DATA: "-----BEGIN KUBEMQ KEY-----eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJMYWJlbHMiOnsidGFnMSI6InRhZzEifSwiYXVkIjoiYSIsImV4\n  cCI6MTAwMDAw\n    MDAwMDAsImp0aSI6InMiLCJpYXQiOjEsImlzcyI6InMiLCJuYmYiOjEsInN1YiI6ImEifQ.PZHLJcgsTaATx1kEvYXitV-2ccbUNrIOhPiNt0qttgjYrcyDzUOGzZv6LLVhqiF1TRnk7j7qdHRA-agyv02sToYkS1sJyQvN6mqMGsNvsad8_JM8WAFJVQNx8Fn673tZGytFM-kwg2bDywX3ex2L3hG6PKcwDhgxyKjOm8Rk52KqU_I5uGXK5kbrVsM3uP78Jc-Ed4cKa2AauPc9vSbXHJ4XCtZIlcw1ks2h8n2Tu8W__eOx_mdkxmT9wwyaY8CdCCkomFI1-xsT_FhC_CivolhTBWDOvQQU-U9BuFK-KwpgBdjwuy1a2OrCEGD9Xol0T5eY22lEKys4__nSG\nX1\nS8A-----END KUBEMQ KEY-----"
  
  AUTHENTICATION_ENABLE: "true"
  AUTHENTICATION_JWT_CONFIG_KEY: "some-type"
  AUTHENTICATION_JWT_CONFIG_SIGNATURE_TYPE: "HS256"
---
# Source: kubemq/templates/environment-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubemq-environment
  labels:
    app.kubernetes.io/name: kubemq
    helm.sh/chart: kubemq-0.3.0
    app.kubernetes.io/instance: kubemq
    app.kubernetes.io/managed-by: Helm
data:
---
# Source: kubemq/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubemq-external
  labels:
    app: kubemq
    chart: "kubemq-0.3.0"
    release: "kubemq"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: api-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc-port
    port: 50000
    protocol: TCP
    targetPort: 50000
  - name: rest-port
    port: 9090
    protocol: TCP
    targetPort: 9090
  sessionAffinity: None
  selector:
    app: kubemq
    release: kubemq
---
# Source: kubemq/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubemq
  labels:
    app: kubemq
    chart: "kubemq-0.3.0"
    release: "kubemq"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
    - name: cluster-port
      port: 5228
      protocol: TCP
      targetPort: 5228
  sessionAffinity: None
  selector:
    app: kubemq
    release: kubemq
---
# Source: kubemq/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubemq
  labels:
    app: kubemq
    chart: kubemq-0.3.0
    heritage: Helm
    release: kubemq
spec:
  selector:
    matchLabels:
      app: kubemq
      release: kubemq
  replicas: 3
  serviceName: kubemq
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubemq
        release: kubemq

    spec:
      containers:
        - env:
            - name: CLUSTER_NAME
              value: kubemq
          envFrom:
            - secretRef:
                name: kubemq
            - configMapRef:
                name: "kubemq-environment"
          image: kubemq/kubemq:dev-v2.0.0.1
          imagePullPolicy: Always
          name: kubemq
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 4
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          ports:
            - containerPort: 50000
              name: grpc-port
              protocol: TCP
            - containerPort: 8080
              name: api-port
              protocol: TCP
            - containerPort: 9090
              name: rest-port
              protocol: TCP
            - containerPort: 5228
              name: cluster-port
              protocol: TCP
          resources:
           limits:
             cpu: 500m
             memory: 512Mi
           requests:
             cpu: 100m
             memory: 256Mi
      restartPolicy: Always

