configFile: ""
existingConfiguration: ""
existingSecret: ""
licenseData: ""
replicaCount: 3

image:
  repository: kubemq/kubemq
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  apiPort: 8080
  restPort: 9090
  grpcPort: 50000
  clusterPort: 5228
  gatewayPort: 7000

security:
  enable: false
  cert: ""
  key: ""
  cacert: ""

authentication:
  enable: false
  key: ""
  type: ""

authorization:
  enable: false
  policyData: ""
  url: ""
  autoReload: 0

gateway:
  enable: false
  gateways: ""
  port: 7000
  cert: ""
  key: ""
  cacert: ""
env:
  apiPort: 8080
  restPort: 9090
  grpcPort: 50000
  clusterPort: 5228
  extra_env_vars: {}
    # Add arbitrary environment variables here:
    # <KEY>: VALUE

livenessProbe:
  enabled: true
  initialDelaySeconds: 4
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 1
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

statefulset:
  updateStrategy: RollingUpdate
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9102'
    prometheus.io/path: '/metrics'

volume:
  enabled: false
  size: 1Gi
  mountPath: './store'
  accessMode: "ReadWriteOnce"

resources: {}
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

nodeSelector: {}
affinity: {}
tolerations: []
