{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "kubemq.fullname" . }}
  labels:
    app: {{ include "kubemq.fullname" .  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
{{- if not .Values.configFile }}
        {{- if .Values.licenseData }}
  LICENSE_KEY_DATA: {{ .Values.licenseData | quote }}
        {{- end }}
        {{- if .Values.authentication.enable }}
  AUTHENTICATION_ENABLE: {{ .Values.authentication.enable | quote}}
  AUTHENTICATION_JWT_CONFIG_KEY: {{ .Values.authentication.key | quote }}
  AUTHENTICATION_JWT_CONFIG_SIGNATURE_TYPE: {{ .Values.authentication.type | quote }}
        {{- end }}
        {{- if .Values.security.enable }}
        {{- if .Values.security.cert }}
  SECURITY_CERT_DATA: {{ .Values.security.cert | quote }}
        {{ end }}
        {{- if .Values.security.key }}
  SECURITY_KEY_DATA: {{ .Values.security.key | quote }}
        {{ end }}
        {{- if .Values.security.cacert }}
  SECURITY_CA_DATA: {{ .Values.security.cacert | quote }}
        {{ end }}
        {{- end}}

        {{- if .Values.gateway.enable}}
          {{- if .Values.gateway.cert}}
  BROKER_GATEWAY_CERT: {{ .Values.gateway.cert | quote}}
          {{- end }}
        {{- if .Values.gateway.key}}
  BROKER_GATEWAY_KEY: {{ .Values.gateway.key | quote}}
        {{- end }}
        {{- if .Values.gateway.cacert}}
  BROKER_GATEWAY_CA: {{ .Values.gateway.cacert | quote}}
        {{- end }}

{{- end}}
{{- end}}
{{ end }}
