apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemq.fullname" . }}-external
  labels:
    app: {{ include "kubemq.fullname" .  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api-port
    port: {{ .Values.service.apiPort }}
    protocol: TCP
    targetPort: {{ .Values.env.apiPort }}
  - name: grpc-port
    port: {{ .Values.service.grpcPort }}
    protocol: TCP
    targetPort: {{ .Values.env.grpcPort }}
  - name: rest-port
    port: {{ .Values.service.restPort }}
    protocol: TCP
    targetPort: {{ .Values.env.restPort }}
  sessionAffinity: None
  selector:
    app: {{ include "kubemq.fullname" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemq.fullname" . }}
  labels:
    app: {{ include "kubemq.fullname" .  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: cluster-port
      port: {{ .Values.service.clusterPort }}
      protocol: TCP
      targetPort: {{ .Values.env.clusterPort }}
        {{-if .Values.gateway.enable}}
    - name: gateway-port
      port: {{ .Values.service.gatewayPort }}
      protocol: TCP
      targetPort: {{ .Values.gateway.port }}
            {{- end }}
  sessionAffinity: None
  selector:
    app: {{ include "kubemq.fullname" . }}
    release: {{ .Release.Name }}
