kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemq-operator
subjects:
  - kind: ServiceAccount
    name: kubemq-operator
roleRef:
  kind: ClusterRole
  name: kubemq-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemq-cluster
subjects:
  - kind: ServiceAccount
    name: kubemq-cluster
roleRef:
  kind: Role
  name: kubemq-cluster
  apiGroup: rbac.authorization.k8s.io
